all:
	gcc criacao_arquivos.c -o criacao_arquivos -Wall
	gcc leitura_arquivos.c -o leitura_arquivos -Wall
	gcc exclusao_arquivos.c -o exclusao_arquivos -Wall

run:
	./criacao_arquivos
	./leitura_arquivos
	./exclusao_arquivos
